apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: AltPackageRepository
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: AltPackageRepository
    apps.tanzu.vmware.com/has-tests: true
spec:
  params:
    - name: run-image
      value: dev.local/AltPackageRepository
  source:
    git:
      url: https://github.com/pacphi/AltPackageRepository
      ref:
        branch: with-tests
  build:
    env:
      - name: BP_DOTNET_PROJECT_PATH
        value: src
